# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: Catnip TCP Ping Pong

concurrency:
  group: azure
  cancel-in-progress: true

on:
  push:
    branches:
      - bugfix-*
      - enhancement-*
      - feature-*
      - workaround-*
      - dev
      - unstable
      - master
  workflow_dispatch:
    branches:
      - bugfix-*
      - enhancement-*
      - feature-*
      - workaround-*
      - dev
      - unstable
      - master

env:
  CARGO_TERM_COLOR: always
  GITHUB_REPOSITORY: $GITHUB_REPOSITORY
  GITHUB_SHA: $GITHUB_SHA

jobs:

  #====================
  # Setup
  #====================

  # Demikernel 0
  setup-demikernel0:
    name: Demikernel 0
    uses: demikernel/workflows/.github/workflows/setup.yml@dev
    secrets:
      host: ${{ secrets.HOSTNAME_A }}
      port: ${{ secrets.PORTNUM_A }}
      key: ${{ secrets.SSHKEY }}
      username: ${{ secrets.USERNAME }}

  # Demikernel 1
  setup-demikernel1:
    name: Demikernel 1
    uses: demikernel/workflows/.github/workflows/setup.yml@dev
    secrets:
      host: ${{ secrets.HOSTNAME_B }}
      port: ${{ secrets.PORTNUM_B }}
      key: ${{ secrets.SSHKEY }}
      username: ${{ secrets.USERNAME }}


  #====================
  # Compile
  #====================

  # Demikernel 0
  build-demikernel0:
    name: Demikernel 0
    needs: [setup-demikernel0]
    uses: demikernel/workflows/.github/workflows/compile.yml@dev
    with:
      target: "all-tests LIBOS=catnip"
    secrets:
      host: ${{ secrets.HOSTNAME_A }}
      port: ${{ secrets.PORTNUM_A }}
      key: ${{ secrets.SSHKEY }}
      username: ${{ secrets.USERNAME }}

  # Demikernel 1
  build-demikernel1:
    name: Demikernel 1
    needs: [setup-demikernel1]
    uses: demikernel/workflows/.github/workflows/compile.yml@dev
    with:
      target: "all-tests LIBOS=catnip"
    secrets:
      host: ${{ secrets.HOSTNAME_B }}
      port: ${{ secrets.PORTNUM_B }}
      key: ${{ secrets.SSHKEY }}
      username: ${{ secrets.USERNAME }}

  #====================
  # Run
  #====================

  # Demikernel 0
  launch-demikernel0:
    name: Demikernel0
    runs-on: ubuntu-latest
    needs: [build-demikernel0, build-demikernel1]
    steps:
    - name: Launch
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTNAME_A }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: ${{ secrets.PORTNUM_A }}
        envs: GITHUB_REPOSITORY,GITHUB_SHA
        script: |
          source $HOME/setup-env.sh
          cd $GITHUB_REPOSITORY
          PEER=server TIMEOUT=300 TEST=tcp_ping_pong_single sudo -E make LIBOS=catnip test-system > nohup.out 2> nohup.err < /dev/null  &

  # Demikernel 1
  launch-demikernel1:
    name: Demikernel 1
    runs-on: ubuntu-latest
    needs: [build-demikernel1, launch-demikernel0]
    steps:
    - name: Launch
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTNAME_B }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: ${{ secrets.PORTNUM_B }}
        envs: GITHUB_REPOSITORY,GITHUB_SHA
        script: |
          source $HOME/setup-env.sh
          cd $GITHUB_REPOSITORY
          PEER=client TIMEOUT=300 TEST=tcp_ping_pong_single sudo -E make LIBOS=catnip test-system > nohup.out 2> nohup.err < /dev/null

  #====================
  # Post-Run
  #====================

  # Demikernel 0
  postrun-demikernel0:
    name: Demikernel 0
    needs: [launch-demikernel1]
    uses: demikernel/workflows/.github/workflows/postrun.yml@dev
    with:
      process-name: pingpong
    secrets:
      host: ${{ secrets.HOSTNAME_A }}
      port: ${{ secrets.PORTNUM_A }}
      key: ${{ secrets.SSHKEY }}
      username: ${{ secrets.USERNAME }}

  # Demikernel 1
  postrun-demikernel1:
    name: Demikernel 1
    needs: [launch-demikernel1]
    uses: demikernel/workflows/.github/workflows/postrun.yml@dev
    with:
      process-name: pingpong
    secrets:
      host: ${{ secrets.HOSTNAME_B }}
      port: ${{ secrets.PORTNUM_B }}
      key: ${{ secrets.SSHKEY }}
      username: ${{ secrets.USERNAME }}

  #====================
  # Cleanup
  #====================

  # Demikernel 0
  cleanup-demikernel0:
    name: Demikernel 0
    needs: [postrun-demikernel0]
    uses: demikernel/workflows/.github/workflows/cleanup.yml@dev
    secrets:
      host: ${{ secrets.HOSTNAME_A }}
      port: ${{ secrets.PORTNUM_A }}
      key: ${{ secrets.SSHKEY }}
      username: ${{ secrets.USERNAME }}

  # Demikernel 1
  cleanup-demikernel1:
    name: Demikernel 1
    needs: [postrun-demikernel1]
    uses: demikernel/workflows/.github/workflows/cleanup.yml@dev
    secrets:
      host: ${{ secrets.HOSTNAME_B }}
      port: ${{ secrets.PORTNUM_B }}
      key: ${{ secrets.SSHKEY }}
      username: ${{ secrets.USERNAME }}
